import 'dart:convert';
import '../../core/services/pocketbase_service.dart';

class ExportService {
  static Future<String> exportEnergyReport() async {
    final buffer = StringBuffer();
    buffer.writeln('═══════════════════════════');
    buffer.writeln('  SYNAPSE ENERGY REPORT');
    buffer.writeln('═══════════════════════════');
    buffer.writeln('Date: ${DateTime.now().toIso8601String()}');
    buffer.writeln('');
    buffer.writeln('User: ${PocketBaseService.pb.authStore.model?.getStringValue('name') ?? 'Unknown'}');
    buffer.writeln('Email: ${PocketBaseService.pb.authStore.model?.getStringValue('email') ?? 'Unknown'}');
    buffer.writeln('');
    
    try {
      final devices = await PocketBaseService.getDevices();
      buffer.writeln('DEVICES (${devices.length}):');
      for (var device in devices) {
        buffer.writeln('  - ${device.data['name']}: ${device.data['is_on'] == true ? 'ON' : 'OFF'}');
      }
    } catch (_) {
      buffer.writeln('Could not load device data.');
    }
    
    buffer.writeln('');
    buffer.writeln('═══════════════════════════');
    buffer.writeln('  Generated by Synapse v1.0');
    buffer.writeln('═══════════════════════════');
    
    return buffer.toString();
  }

  static Future<Map<String, dynamic>> exportAsJson() async {
    final devices = await PocketBaseService.getDevices();
    
    return {
      'app': 'Synapse',
      'version': '1.0.0',
      'exportDate': DateTime.now().toIso8601String(),
      'user': {
        'name': PocketBaseService.pb.authStore.model?.getStringValue('name') ?? 'Unknown',
        'email': PocketBaseService.pb.authStore.model?.getStringValue('email') ?? 'Unknown',
      },
      'devices': devices.map((d) => {
        'name': d.data['name'],
        'type': d.data['type'],
        'isOn': d.data['is_on'],
        'created': d.created,
      }).toList(),
      'totalDevices': devices.length,
      'activeDevices': devices.where((d) => d.data['is_on'] == true).length,
    };
  }

  static String formatJson(Map<String, dynamic> data) {
    return const JsonEncoder.withIndent('  ').convert(data);
  }
}